tech_blog/blog/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.PostListView.as_view(), name = 'post_list'),
    path('about/', views.AboutView.as_view(), name = 'about'),
    path('post/<int:pk>', views.PostDetailView.as_view(), name = 'post_detail'),
    path('post/new/', views.CreatePostView.as_view(), name = 'post_new'),
    path('post/<int:pk>/edit/', views.PostUpdateView.as_view(), name = 'post_edit'),
    path('post/<int:pk>/remove/', views.PostDeleteView.as_view(), name = 'post_remove'),
    path('drafts/', views.DraftListView.as_view(), name = 'post_draft_list'),
    path('post/<int:pk>/comment/', views.add_comment_to_post, name = 'add_comment_to_post'),
    path('comment/<int:pk>/approve/', views.comment_approve, name = 'comment_approve'),
    path('comment/<int:pk>/remove/', views.comment_remove, name = 'comment_remove'),
    path('post/<int:pk>/publish/', views.post_publish, name = 'post_publish'),
    path('accounts/login/', LoginView.as_view(), name = 'login'),
    path('accounts/logout/', LogoutView.as_view(), name = 'logout', kwargs = {'next_page' : ''})
]

tech_blog/tech_blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls'))
]

tech_blog/blog/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse

# Create your models here.

class Post(models.Model):
    author = models.ForeignKey('auth.User', on_delete = models.CASCADE)
    title = models.CharField(max_length = 200)
    text = models.TextField()
    create_date = models.DateTimeField(default = timezone.now)
    published_date = models.DateTimeField(blank = True, null = True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def approve_comments(self):
        return self.comments.filter(approved_comment = True)

    def get_absolute_url(self):
        return reverse('blog:post_detail', kwargs = {'pk' : self.pk})

    def __str__(self):
        return self.title

class Comment(models.Model):
    post = models.ForeignKey(Post, related_name = 'comments', on_delete = models.CASCADE)
    author = models.CharField(max_length = 200)
    text = models.TextField()
    create_date = models.DateTimeField(default = timezone.now)
    approved_comment = models.BooleanField(default = False)

    def approve(self):
        self.approved_comment = True
        self.save()

    def get_absolute_url(self):
        return reverse('blog:post_list')

    def __str__(self):
        return self.text

tech_blog/blog/forms.py
from django import forms
from . import models

class PostForm(forms.ModelForm):
    class Meta:
        model = models.Post
        fields = ('author', 'title', 'text')

        widgets = {
            'title' : forms.TextInput(attrs = {'class' : 'text-input'}),
            'text' : forms.Textarea(attrs = {'class' : 'editable medium-editor-textarea post-content'})
        }

class CommentForm(forms.ModelForm):
    class Meta:
        model = models.Comment
        fields = ('author', 'text')

        widgets = {
            'author' : forms.TextInput(attrs = {'class' : 'text-input'}),
            'text' : forms.Textarea(attrs = {'class' : 'editable medium-editor-textarea post-content'})
        }

tech_blog/blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView
from django.utils import timezone
from . import models, forms
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy

# Create your views here.

class AboutView(TemplateView):
    template_name = 'about.html'

class PostListView(ListView):
    model = models.Post

    # Field lookups
    def get_queryset(self):
        return models.Post.objects.filter(published_date__lte = timezone.now()).order_by('-published_date')

class PostDetailView(DetailView):
    model = models.Post

class CreatePostView(LoginRequiredMixin, CreateView):
    login_url = 'login/'
    redirect_field_name = 'blog/post_detail.html'
    form_class = forms.PostForm
    model = models.Post

class PostUpdateView(LoginRequiredMixin, UpdateView):
    login_url = 'login/'
    redirect_field_name = 'blog/post_detail.html'
    form_class = forms.PostForm
    model = models.Post

class PostDeleteView(LoginRequiredMixin, DeleteView):
    login_url = 'login/'
    success_url = reverse_lazy('blog:post_list')
    model = models.Post

class DraftListView(LoginRequiredMixin, ListView):
    login_url = 'login/'
    redirect_field_name = 'blog/post_list.html'
    template_name = 'blog/post_draft_list.html'
    model = models.Post

    def get_queryset(self):
        return models.Post.objects.filter(published_date__isnull = True).order_by('create_date')

###################################################

@login_required
def add_comment_to_post(request, pk):
    post = get_object_or_404(models.Post, pk = pk)
    form = forms.CommentForm()
    
    if request.method == 'POST':
        form = forms.CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit = False)
            comment.post = post
            comment.save()
            return redirect('blog:post_detail', pk = post.pk)
    
    return render(request, 'blog/comment_form.html', {'form' : form})

@login_required
def comment_approve(request, pk):
    comment = get_object_or_404(models.Comment, pk = pk)
    comment.approve()
    return redirect('blog:post_detail', pk = comment.post.pk)

@login_required
def comment_remove(request, pk):
    comment = get_object_or_404(models.Comment, pk = pk)
    post_pk = comment.post.pk
    comment.delete()
    return redirect('blog:post_detail', pk = post_pk)

@login_required
def post_publish(request, pk):
    post = get_object_or_404(models.Post, pk = pk)
    post.publish()
    return redirect('blog:post_detail', pk = pk)

tech_blog/blog/templates/blog/about.html
{% extends 'blog/base.html' %}

{% block content %}
    <h2>About me</h2>
{% endblock %}

tech_blog/blog/templates/blog/base.html
<!DOCTYPE html>

{% load staticfiles %}

<html>
    <head>
        <meta charset="utf-8">
        <title>Blog</title>

        <!-- Bootstrap -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-glyphicons.css" rel="stylesheet">

        <!-- Medium Style Editor -->
        <script src="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/js/medium-editor.min.js"></script>
        <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/css/medium-editor.min.css" type="text/css" media="screen" charset="utf-8">

        <!-- Custom CSS -->
        <link rel="stylesheet" href="{% static '.css/blog.css' %}">

        <!-- Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Muli&display=swap" rel="stylesheet">
    </head>

    <body>
        <!-- Navbar -->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container">
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav tech-font">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'blog:post_list' %} ">Tech Blog</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'blog:about' %} ">About</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="https://www.github.com/sonicaks/">Github</a>
                        </li>
                    </ul>

                    <ul class="navbar-nav ml-auto tech-font">
                        {% if user.is_authenticated %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'blog:post_new' %} ">New Post</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'blog:post_draft_list' %} ">Drafts</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'blog:logout' %} ">Logout</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#">Welcome: {{ user.username }}</a>
                            </li>
                        {% else %}
                            <li class="nav-item">
                                <a href="{% url 'blog:login' %} "><span class="glyphicon glyphicon-user"></span></a>
                            </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>

        <!-- Content -->
        <div class="container">
            <div class="row">
                <div class="col-md-8">
                    <div class="blog-posts">
                        {% block content %}
                        {% endblock %}
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>

tech_blog/blog/templates/blog/comment_form.html
{% extends 'blog/base.html' %}

{% block content %}
    <h1>New Comment</h1>
    <form class="post-form" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-primary">Post Comment</button>
    </form>

    <script>
    var editor = new MediumEditor('.editable');
    </script>
{% endblock %}

tech_blog/blog/templates/blog/post_confirm_delete.html
{% extends 'blog/base.html' %}

{% block content %}
    <form method="POST">
        {% csrf_token %}
        <p>Are you sure you want to delete {{ object }} ?</p>
        <input type="submit" class="btn btn-danger" value="Confirm">
    </form>
{% endblock %}

tech_blog/blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}

{% block content %}
    <h1 class="post-title">{{ post.title }}</h1>
    {% if post.published_date %}
        <div class="date post-date">
            {{ post.published_date }}
        </div>
    {% else %}
        <a class="btn btn-primary" href="{% url 'blog:post_publish' pk=post.pk %}">Publish</a>
    {% endif %}

    <p class="post-content">{{ post.text|safe|linebreaksbr }}</p>

    {% if user.is_authenticated %}
        <a class="btn btn-primary" href="{% url 'blog:post_edit' pk=post.pk %}"><span class="glyphicon glyphicon-pencil"></span></a>
        <a class="btn btn-primary" href="{% url 'blog:post_remove' pk=post.pk %}"><span class="glyphicon glyphicon-remove"></span></a>
    {% endif %}

    <hr>
    
    <a class="btn btn-primary btn-comment" href="{% url 'blog:add_comment_to_post' pk=post.pk %}">Comment</a>

    <div class="container">
        {% for comment in post.comments.all %}
        <br>
            {% if user.is_authenticated or comment.approved_comment %}
                {{ comment.create_date }}
                {% if not comment.approved_comment %}
                    <a class="btn btn-default" href="{% url 'blog:comment_remove' pk=comment.pk %}"><span class="glyphicon glyphicon-remove"></span></a>
                    <a class="btn btn-primary" href="{% url 'blog:comment_approve' pk=comment.pk %}"><span class="glyphicon glyphicon-ok"></span></a>
                {% endif %}
                <p>{{ comment.text|safe|linebreaks }}</p>
                <p>Posted by: {{ comment.author }}</p>
            {% endif %}
            {% empty %}
                <p>No comments</p>
        {% endfor %}
    </div>

{% endblock %}

tech_blog/blog/templates/blog/post_draft_list.html
{% extends 'blog/base.html' %}

{% block content %}
    {% for post in post_list %}
        <div class="post">
            <h1><a href="{% url 'blog:post_detail' pk=post.pk %}">{{ post.title }}</a></h1>
            <p class="date">Created: {{ post.create_date|date:'D M Y' }}</p>
            <p>{{ post.text|safe|truncatechars:200 }}</p>
        </div>
    {% endfor %}
{% endblock %}

tech_blog/blog/templates/blog/post_form.html
{% extends 'blog/base.html' %}

{% block content %}
    <h1>New Post</h1>
    <form class="post-form" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-primary">Save</button>
    </form>

    <script>
        var editor = new MediumEditor('.editable');
    </script>
{% endblock %}

tech_blog/blog/templates/blog/post_list.html
{% extends 'blog/base.html' %}

{% block content %}
    <div class="center-stage">
        {% for post in post_list %}
            <div class="post">
                <h1><a href="{% url 'blog:post_detail' pk=post.pk %}">{{ post.title }}</a></h1>
            </div>
            <div class="date">
                <p>Published on: {{ post.published_date|date:"D M Y" }}</p>
            </div>
            <a href="{% url 'blog:post_detail' pk=post.pk %}">Comments: {{ post.approve_comments.count }}</a>
        {% endfor %}
    </div>
{% endblock %}